spring:
  application:
    name: taskmanager
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true