spring:
  main:
    banner-mode: "off"
  config:
    activate:
      on-profile: prod
  flyway:
    locations: classpath:db/migration,classpath:db/postgresql
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}
    refresh-secret: ${JWT_REFRESH_SECRET}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}